name: quan_ly_giao_thong_remote
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.3
  socket_io_client: ^3.1.2
  video_player: ^2.8.1
  chewie: ^1.7.1
  http: ^1.1.0
  shared_preferences: ^2.2.0
  camera: ^0.11.1
  cupertino_icons: ^1.0.2
  mqtt_client: ^10.0.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.0
  provider: ^6.0.5
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
