name: quan_ly_giao_thong
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  provider: ^6.1.1
  geolocator: ^10.1.0
  mqtt_client: ^10.2.0
  shared_preferences: ^2.2.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
